### PR TITLE
Update example notebooks

### PR DESCRIPTION
**Pull request by peterm790**
The methods used to start clusters on the original 'ike' notebook examples did not work on the esip jupyter lab. These notebooks have been updated to match the methods used in other examples

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@peterm790, please strip the output of the notebook first -- that way we can see what actually changed in the code.

**Comment by martindurant** [comment]
The easy way to do that without installing the nbstrip tool or any pre-commit thing, is to open the notebook in jupyter and clear all output - It think in the edit menu.

**Comment by peterm790** [comment]
I have added another commit with the notebook outputs stripped, I ended up using the nbstripout tool. However I'm not sure if you can see the diffs from the original to the second commit?

**Comment by rsignell-usgs** [comment]
@peterm790 , indeed, because there are notebooks currently in the main branch with output, if you submit a PR with output stripped, you won't easily be able to see the changes.   But once all latest committed notebooks in main have output stripped, future PRs with stripped notebooks should work nicely.    So I'll merge this PR.

**Pull request merged**
